name = "Bayesutil"
uuid = "e5f1a4da-233a-4dd3-8663-4f0408ac6084"
authors = ["Rajesh Talluri"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
